version: "3"

services:
  auth_service:
    build: ./auth_service/.
    ports:
      - "8083:8083"
  post_service:
    build: ./post_service/.
    ports:
      - "8082:8082"
  user_service:
    build: ./user_service/.
    ports:
      - "8081:8081"
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx-config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-config/api_conf.d/:/etc/nginx/api_conf.d/:ro
      - ./nginx-config/api_backends.conf:/etc/nginx/api_backends.conf:ro
      - ./nginx-config/api_gateway.conf:/etc/nginx/api_gateway.conf:ro
      - ./nginx-config/api_json_errors.conf:/etc/nginx/api_json_errors.conf:ro
      - ./nginx-config/api_keys.conf:/etc/nginx/api_keys.conf:ro
    depends_on:
      - auth_service
      - post_service
      - user_service
    